name: beer_barrel
description: online beer barrel.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^12.0.0
  cached_network_image: ^3.3.0
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.0.0
  mockito: ^5.4.2
  linkedin_login: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/app_logo/
    - assets/facebook_logo/
    - assets/google_logo/
    - assets/linkedin_logo/

  fonts:
    - family: sf-pro-text
      fonts:
        - asset: assets/fonts/sf-pro-text-bold.ttf
        - asset: assets/fonts/sf-pro-text-heavy.ttf
        - asset: assets/fonts/sf-pro-text-medium.ttf
        - asset: assets/fonts/sf-pro-text-regular.ttf
          weight: 900

